### ISSUE TITLE
Add plotly as a requirement

### ISSUE THREAD

**Issue by twolodzko** [neptune-ai/neptune-contrib#101]
The `log_chart` functionality depends on plotly, but plotly is not mentioned as a dependence for the package.

**Comment by jakubczakon** [comment]
Thanks for spotting that @twolodzko 

I think it uses plotly only if you are logging plotly or matplotlib figures. 

That said, it needs to be mentioned somewhere explicitly -> we'll fix that.

**Comment by jakubczakon** [comment]
It seems that on the newest versions of matplotlib and plotly `log_chart` failes due to this [plotly issue](https://stackoverflow.com/questions/63120058/plotly-mpl-to-plotly-error-spine-object-has-no-attribute-is-frame-like).

For now in order to make it work you need to downgrade matplotlib -> `pip install matplotlib==3.2.2` as I've done in [this experiment](https://ui.neptune.ai/o/shared/org/LightGBM-integration/e/LGBM-61/artifacts?path=charts%2F&file=Precision-Recall%20Curve.html).
