### ISSUE TITLE
Support for fastai 2.x?

### ISSUE THREAD

**Issue by pcnudde** [neptune-ai/neptune-contrib#104]
Any plans to update fastai support to 2.x?

**Comment by jakubczakon** [comment]
Thanks for bringing it up @pcnudde!

The good news is, we are already integrated just via fastai2 -> [see it here](https://github.com/fastai/fastai2/blob/master/fastai2/callback/neptune.py) 

We should have had it in the docs though (apologies @pcnudde) ->
@kamil-kaczmarek could you add info about it to the docs (since you created it)?

**Comment by kamil-kaczmarek** [comment]
Hi @pcnudde and @jakubczakon ,

Sure, I will make proper changes in our docs.

One note: fastai2 is now fastai -> old one was replaced 2-3 week ago. Our integration is here: https://github.com/fastai/fastai/blob/master/fastai/callback/neptune.py

Here are fastai docs about our integration: https://docs.fast.ai/callback.neptune

**Comment by pcnudde** [comment]
Thanks I did not think of looking in the fast.ai documentation.
