### ISSUE TITLE
different way of disambiguating binary_classification_metrics

### ISSUE THREAD

**Issue by kretes** [neptune-ai/neptune-contrib#121]
Hello,

I started to use `log_binary_classification_metrics`, which is quite handy.
I've incorporated it into an evaluation pipeline, which is run every N steps while training. That is fine as for the numeric variables this method logs to neptune. However the super-handy `metric_charts` are all added to a single big 'bucket' in neptune, and I cannot understand which charts are from which epoch/step.
see e.g. here I have logged this twice and I have two confusion matrices, etc...:
![image](https://user-images.githubusercontent.com/1224887/101825504-fbdc0680-3b2d-11eb-82f1-282fba1b90d2.png)

I could use the 'prefix' parameter to `log_binary_classification_metrics`, and store epoch/step numer there - but this makes my metrics messy, as every numeric parameter at every step start to have different name.
what I suggest is either:
1. one can pass additional parameter like 'title', which would be included in the title of every generated image
2. make 'prefix' work only for charts?

you may have other ideas on how to solve this problem easily, I hope I made it understandable

**Comment by jakubczakon** [comment]
Hi @kretes,
I think I understand your use case.  

It's important to mention that this method was created to log things once and put them all in one log space (probably I should add this use-case explicitly in the docs). 

That said you can definitely log those charts every N iterations. 
My suggestions are (I've added examples in Neptune so that you can see how it looks like):

If you want to log metrics during training I'd suggest doing something like this:

```python
for i in range(iterations):

    log_cumulative_gain(y_true, y_pred, channel_name='cummulative_gain_charts', description=f'epoch {i}')
     
```

**Log as image to logs**
where the log_cumulative_gain is modified to something like this:

```python

def log_cumulative_gain(y_true, y_pred, experiment=None, channel_name='cummulative_gain_charts', iteration=None):
    assert len(y_pred.shape) == 2, 'y_pred needs to be (n_samples, 2), use expand_prediction helper to format it'

    _exp = experiment if experiment else neptune

    fig, ax = plt.subplots()
    plt_metrics.plot_cumulative_gain(y_true, y_pred, ax=ax)
    _exp.log_image(channel_name, fig, description='epoch {}'.format(epoch))
    plt.close()
```
[Example in neptune](https://ui.neptune.ai/shared/showroom/e/SHOW-2198/logs)

It uses [log_image](https://docs.neptune.ai/api-reference/neptune/experiments/index.html#neptune.experiments.Experiment.log_image) method which at the time of creating `log_binary_classification_metrics` wasn't working with matplotlib figures. 

**Log as .png/interactive ploty to artifacts**

Alternatively, you could also [log those charts into artifacts. (https://docs.neptune.ai/logging-and-managing-experiment-results/logging-experiment-data.html#logging-experiment-data-interactive-charts-matplotlib) and add epoch name to the artifact filename. Unfortunately due to the incompatibility of matplolitb and plotly (and the conversion method being deprecated) this will likely log the chart as .png files rather than interactive plotly charts. 

[Example in neptune](https://ui.neptune.ai/shared/showroom/e/SHOW-2197/artifacts?path=charts%2Fheatmaps%2F&file=epoch1.png)

```python

def log_cumulative_gain(y_true, y_pred, experiment=None, channel_name='cummulative_gain_charts', iteration=None):
    assert len(y_pred.shape) == 2, 'y_pred needs to be (n_samples, 2), use expand_prediction helper to format it'

    _exp = experiment if experiment else neptune

    fig, ax = plt.subplots()
    plt_metrics.plot_cumulative_gain(y_true, y_pred, ax=ax)
    log_chart('cumulative_gain/epoch_{}'.format(epoch), fig, _exp)

    plt.close()
```

**Comment by jakubczakon** [comment]
Did this help @kretes?

**Comment by kretes** [comment]
@jakubczakon I know I could get the functionality I ask for by using lower-lever api of calcuating and pushing graphs & metrics.

maybe I am overusing the `log_binary_classification_metrics` (as users always do with libraries ;-) ) - right now I just run it at the end of the training and this is fine. I just don't get all the metrics graphs from it and am doing metrics on my own

**Comment by jakubczakon** [comment]
Got it, sorry :) the original intention was to use it after training. 

But I think your use case is actually very valuable and not that uncommon. 
 
I'll tag this with enhancement and let the dev team know.

**Comment by kamil-kaczmarek** [comment]
closing this let's move future discussion here: https://github.com/neptune-ai/neptune-client/issues
